name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - dev

env:
  DOCKER_IMAGE: rafaelmartinswen/portal-rpa-gpssa-node:latest
  CONTAINER_APP_NAME: portal-rpa-backend-dev
  RESOURCE_GROUP: GPS_RPA_PRODUCAO

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do c√≥digo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DEV }}

      # Build da imagem
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      # Push para Docker Hub
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

      # Login na Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy para Azure Container Apps
      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $DOCKER_IMAGE
